apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-client
  labels:
    app: world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello-client
        image: kvaradha/hello-world-client
        args:
          - --host=hello-world-service
          - --port=6543
