apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  labels:
    service: hello
spec:
  type: NodePort
  ports:
    - name: http
      port: 6543
      targetPort: 65432
  selector:
    app: hello
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-server
  labels:
    app: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello-server
        image: kvaradha/hello-world-server
        ports:
        - containerPort: 65432
